version: "3.3"

services:

  flask:
    build: .
    container_name: flask
    restart: always
    env_file: .env
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  my-mysql:
    image: "mysql/mysql-server:5.7"
    restart: always
    env_file: ./db/.env-mysql
    volumes:
      - ${PWD}/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
