version: "3.3"

services:

  flask:
    build: .
    container_name: flask
    restart: always
    env_file: .env
    links:
      - my-mysql:dbserver
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:80"

  my-mysql:
    image: "mysql:latest"
    restart: always
    env_file: .env-mysql
    ports:
    - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
