"""empty message

Revision ID: 2367cc2eaa32
Revises: 
Create Date: 2021-02-22 09:56:13.819251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2367cc2eaa32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_salesRepEmployeeNumber'), 'customers', ['salesRepEmployeeNumber'], unique=False)
    op.drop_constraint('customers_ibfk_1', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'employees', ['salesRepEmployeeNumber'], ['employeeNumber'], ondelete='CASCADE')
    op.create_index(op.f('ix_employees_officeCode'), 'employees', ['officeCode'], unique=False)
    op.create_index(op.f('ix_employees_reportsTo'), 'employees', ['reportsTo'], unique=False)
    op.drop_constraint('employees_ibfk_1', 'employees', type_='foreignkey')
    op.drop_constraint('employees_ibfk_2', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'offices', ['officeCode'], ['officeCode'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employees', 'employees', ['reportsTo'], ['employeeNumber'], ondelete='CASCADE|SET NULL')
    op.create_index(op.f('ix_orderdetails_productCode'), 'orderdetails', ['productCode'], unique=False)
    op.drop_constraint('orderdetails_ibfk_1', 'orderdetails', type_='foreignkey')
    op.drop_constraint('orderdetails_ibfk_2', 'orderdetails', type_='foreignkey')
    op.create_foreign_key(None, 'orderdetails', 'products', ['productCode'], ['productCode'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orderdetails', 'orders', ['orderNumber'], ['orderNumber'], ondelete='CASCADE')
    op.create_index(op.f('ix_orders_customerNumber'), 'orders', ['customerNumber'], unique=False)
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customers', ['customerNumber'], ['customerNumber'], ondelete='CASCADE')
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'customers', ['customerNumber'], ['customerNumber'], ondelete='CASCADE')
    op.create_index(op.f('ix_products_productLine'), 'products', ['productLine'], unique=False)
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'productlines', ['productLine'], ['productLine'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'productlines', ['productLine'], ['productLine'])
    op.drop_index(op.f('ix_products_productLine'), table_name='products')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'customers', ['customerNumber'], ['customerNumber'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'customers', ['customerNumber'], ['customerNumber'])
    op.drop_index(op.f('ix_orders_customerNumber'), table_name='orders')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.create_foreign_key('orderdetails_ibfk_2', 'orderdetails', 'products', ['productCode'], ['productCode'])
    op.create_foreign_key('orderdetails_ibfk_1', 'orderdetails', 'orders', ['orderNumber'], ['orderNumber'])
    op.drop_index(op.f('ix_orderdetails_productCode'), table_name='orderdetails')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_ibfk_2', 'employees', 'offices', ['officeCode'], ['officeCode'])
    op.create_foreign_key('employees_ibfk_1', 'employees', 'employees', ['reportsTo'], ['employeeNumber'])
    op.drop_index(op.f('ix_employees_reportsTo'), table_name='employees')
    op.drop_index(op.f('ix_employees_officeCode'), table_name='employees')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_ibfk_1', 'customers', 'employees', ['salesRepEmployeeNumber'], ['employeeNumber'])
    op.drop_index(op.f('ix_customers_salesRepEmployeeNumber'), table_name='customers')
    # ### end Alembic commands ###
